### ISSUE TITLE
Add targetdistance_perc column

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#12]
There should be a column that says what the target distance is in percentage of the maximum allowed. 

I'm not sure what the unit name would be as this is a new unit that we should add to the labs unit definitions.

Apart from 'perc', I can also see 'percmax', 'prop' or 'propmax' making sense. I prefer percentage as that allows for whole integer numbers as they are generated by the GUI (or should be), which prevents rounding errors perhaps. It also somewhat implies that 100 is the maximum, so that we don't have to add that to the name. Any thoughts on potentially harmful effects of this variable name, or does this make sense?

**Comment by juliusjgm12** [comment]
I don't see the variable name being an issue, i can add this. So 100 is maximum and 50 is minimum?

**Comment by thartbm** [comment]
Indeed: 100 is maximum and 50 is minimum (in the interface for the PyVMEC 1.0 at least).

For now, let's use this variable name:

targetdistance_percmax

So its in percentages of the maximum, we also want to have pixel coordinates (targetx_px and targety_px) relative to the home position, so people can calculate the pixel distance if they want.
