### ISSUE TITLE
Save experiment in JSON

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#16]
I'd like to have all output human-readable - in principle. This would most likely only be useful for us to see if the saved JSON file actually has all the info we want. It also allows me to check if stuff is in the places it should be: they should be maximally flexible to allow settings to be editable in the advanced version, even if we hardcode them to certain values right now.

**Comment by juliusjgm12** [comment]
The saved JSON files seem to show all the dictionaries as they were written in python.
It surely is much easier to read than the pickle files.
