### ISSUE TITLE
Run full-screen

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#19]
The experiment should run in full-screen mode.

**Comment by juliusjgm12** [comment]
I keep the experiment running windowed for the moment as i'm making changes. It makes it easier to exit the psychopy window if it gets stuck. There's a boolean in the GUI around line 54 under "general configurations settings" called self.FULLSCREEN. In case I push the changes and forget to change this, if you set this to value to True the experiment will run in fullscreen.
