### ISSUE TITLE
Terminal Feedback option

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#21]
On cursor trials, and maybe on error-clamp trials, there should be an option to switch to terminal feedback. This means that on the outward movement the cursor is also invisible. It is only shown at one location, that location should be slightly beyond the distance of the target (let's say, about half a target diameter further) and with the same angle as the first sample that was further than the target from home. It should stay on for a while (not sure yet how to determine this, for now maybe set to 500 ms) but not move, and then people return back to the home position with the same type of arrow feedback that will be used on no-cursor and error-clamp trials.

**Comment by juliusjgm12** [comment]
For cursor trials or no-cursor trials? Sorry i'm confused, because I thought the cursor is always visible for cursor trials.

**Comment by thartbm** [comment]
On no-cursor trials there is no cursor at all. On cursor trials and error-clamp trials, the cursor could be shown continuously or only terminal. These are two standard ways to give cursor feedback, so you might imagine a part of the interface with an option 'Feedback' that has some options in a radio menu:

Feedback:
o Continuous
o Terminal
o ...

And we might add options later, but not now.
