### ISSUE TITLE
record cursor rotation in output

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#32]
currently there is no column with the cursor rotation, please add?

**Comment by juliusjgm12** [comment]
Added as the angle times polarity

Although I don't know if you want it to show in a single column with
direction specified by the polarity of the angle.

Or if you want just the magnitude of rotation and clockwise or
counterclockwise in a separate column?

**Comment by thartbm** [comment]
angle * polarity sounds great!
