### ISSUE TITLE
wx version problem

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#33]
Linux seems to use wxPython==3.0.x while pip install wxPython==4.0.x
How do we solve this?

**Comment by juliusjgm12** [comment]
The easiest way would be to downgrade the version of wxPython in my opinion. It shouldn't be too difficult, i'll look more online on how this is done properly.

**Comment by thartbm** [comment]
Erm, I can't pip install wxPython==3.x.x.x the only available versions are 4.0.x versions. So upgrading on Linux would be an option, but that means upgrading to 'unstable' versions:

https://packages.debian.org/sid/python-wxgtk4.0

Some of the dependencies will also have to be installed from there... or we can try pip on Linux, but I don't feel like rebuilding my system for an error here.

**Comment by juliusjgm12** [comment]
Do you have to use pip to install it for windows?

There's a sourceforge link with wxpython 3.0.2 executables i found here:
https://sourceforge.net/projects/wxpython/files/wxPython/3.0.2.0/

I'm not sure how to build from them though.

**Comment by thartbm** [comment]
But those don't necessarily work with other components. Pip takes care of making everything compatible. I will try that though - but later, no more time tonight...
