### ISSUE TITLE
Re-organize GUI.

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#38]
I guess all the buttons pertaining to a specific experiment should be grouped below the list of experiments, not below the list of participants. (new/rename/delete and save/load/run)

The participant list should come below that, and then below the participant list I would probably put the button for pre-processing all the participants in the experiment. I'm still not so sure where the experiments settings button should be... but maybe next to the "process" button?

**Comment by juliusjgm12** [comment]
I've put the pre-process button below the participants list and the settings button above the experiments list. As well as putting every experiment related button below the experiments list.
