### ISSUE TITLE
number of trials in drop-down list

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#4]
Put number of trials in a drop-down list. So that people don't have to hit the up/down button hundreds of times but can simply scroll dow,

**Comment by juliusjgm12** [comment]
I think the spin wheel is better. You can press and hold the up/down button to quick zoom to a higher number. Also you can click in the text box and write down a number and I programmed it to automatically round to the nearest appropriate number of trials depending on the number of targets.

What do you think?
