### ISSUE TITLE
no rotation or terminal feedback possible on error-clamp trials

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#47]
This would have to be implemented at some point, but they are rather strange, so we'll just leave that for some other time.

**Comment by juliusjgm12** [comment]
Need some clarification on what this means :cry:

**Comment by thartbm** [comment]
I think you already have terminal feedback for error-clamp trials, so that's fine. What would happen in error-clamped trials with a rotation is that the cursor will always MISS the target by however much the rotation is. So the cursor will go straight to the target angle _plus the rotation_. Does this help?

Technically, those would not be called "error" clamped trials anymore (since the error is not 0), but fall in a larger category of visually clamped trials... you could rename them, or we stick with error-clamped for now.

**Comment by juliusjgm12** [comment]
Should work now, with rotation angle and terminal feedback. The terminal feedback multiplier (distance beyond the workspace arc) that determines where the terminal feedback begins and the terminal feedback duration are adjustable in the GUI.py file but not in the GUI itself. I doubt you want that to be a mutable option but in the case you want to change them at some point.

The values are in GUI.py as:

self.current_experiment[self.highlit_task_num]['terminal_multiplier']
and
self.current_experiment[self.highlit_task_num]['terminal_feedback_time']
