### ISSUE TITLE
number of trials need to be limited

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#5]
There are several limits to the number of targets that make sense given other settings:

1) Number of trials needs to go up by the number of targets, and the minimum should also be the number of targets.
2) In case of gradually introduced rotations, the minimum number of trials should be:

ceiling(rotation/targets) + targets

BUT: for these limits, the number of targets (both in issues 1 and 2) is usually the actual number of targets, except when the number of targets is 1 or 2, then they are increased by 2 to 3 and 4 respectively.

**Comment by juliusjgm12** [comment]
Not sure if the gradual minimum number of trials I implemented is correct for some values.

For example, with a rotation angle of 30 degrees and 4 targets, should the minimum number of trials be 13? I'm unsure because this introduces one extra trial after 3 blocks and i'm not sure if this is the way you want it.

**Comment by thartbm** [comment]
Thanks for noticing this! The formula in the original issue is actually wrong... sorry about that. It should be:

(ceiling(rotation/targets) * target) + targets

The rotation should increases by 1 degree every trial, and there should be one block of trials (i.e. every target at least once) with the full rotation. For 30 degrees and 4 target, that would be: 36 trials minimum (or 9 blocks). The full rotation is reached within the 8th block: ceiling(rotation/targets), which still has to be multiplied by the number of targets to get the right number of trials. And then we add at least one additional block of N targets.

Does this make more sense?

**Comment by juliusjgm12** [comment]
Ahh okay that makes much more sense!

Cheers!

Julius

**Comment by juliusjgm12** [comment]
Hey Marius,

Sorry, something came up this morning so I'll be a bit delayed but I'm omw.
