### ISSUE TITLE
Participant list in main GUI: only 'continue run' when applicable

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#65]
We need some tests to allow the 'continue run' button to be pressed:
- there should not be a complete/final datafile for that participant
- the data that is there should be compatible with the existing experiment (every trial has the right target / rotation / trial type according to the definition)

Maybe we should color participants light grey when they have incomplete but compatible data, and mark them red when they have incompatible data?

**Comment by thartbm** [comment]
This should use the function described elsewhere to generate participant lists. Upon loading an experiment, call the function and show only participants in lists 0 and 1.

Only for participants in list 1 should there be an option to 'continue run'.

If there are any participants in list 2, we might show a pop up with a warning?

**Comment by juliusjgm12** [comment]
I tried different methods using ansi escape strings to integrate color into strings for the participants but it doesn't seem to work for wxpython.

This would be the same method I'd need to use to underline or add italics to individual strings in the participants list box so those won't work either.

Instead, I'm thinking of adding a number code (as in the function you described generating the participant dictionary). I would add the corresponding number to a string 0,1,2,3 depending on where a participant lies in the generated participant dictionary.

What do you think?

**Comment by thartbm** [comment]
Maybe put brackets [] or parentheses () around incomplete participant IDs?

Or my earlier idea: have two separate lists... and a bigger GUI.

**Comment by juliusjgm12** [comment]
Sure, i'm thinking square brackets for incomplete participant IDs and ~ tilde markers for non-matching participants.

**Comment by thartbm** [comment]
I'd not show the non-matching ones... I think? How about we have tick marks so people can pick if they want incomplete or non-matching participants? Not now, perhaps in a future release!

**Comment by juliusjgm12** [comment]
Uhmmm... Well for now I've added the tilde and square brackets. I think it's good to have the non-matching participants there so students can go in and delete that participant if they wish.

Having a tick marker is a good idea though!

**Comment by thartbm** [comment]
Yes, but that requires lots of extra coding. I'm just worried that people will confuse the two. Of the two (incomplete / non-matching), the incomplete are most easily fixed, you continue the run. The non-matching you can't fix, but they won't be incorporated in the data pre-processing anyway, so I'm thinking that not showing them will give students a more accurate assessment of how much data they have or still need to collect for an adequate dataset.

So I see two alternatives:
- don't show the non-matching ones, this has my preference (they can delete them or not, doesn't matter)
- or change the way they're displayed [participant: INCOMPLETE] or [participant: NON-MATCHING], and add another button below the participant list: 'Delete participant'

Actually, I think you can change the text / function of a button dynamically in WX, so there could be a single button, that changes it's look and function depending on the participant's state:

COMPLETE & MATCHING: re-combine data
MATCHING but INCOMPLETE: continue run
NON-MATCHING: delete

But again, the simpler solution is to just not show the non-matching ones... at least for now. That way no-one is confused about anything, and you can keep the buttons and everything just the way it is.
