### ISSUE TITLE
Preprocessing two-stage outlier removal

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#66]
We discussed this already, but I want to extend it:

Before running the standard deviation based outlier removal on the data, we do a first stage to remove big offenders. Reaches that are outside a +/- 45 degree window around the target are OK.

But this should be adapted for the current rotation. Depending on the direction of the rotation and whether the user wants cursor errors or reach deviations, one side of the window should be extended.

There is still a problem with previous rotations. So either we writing some very intelligent code, or we leave it to experimenter. For now, we will do the latter.

- each outlier removal step should be optional, but they are selected by default, with a 45 degree tolerance on either side of the target, and 2 standard deviations selected
- the acceptable window step should always be done before the standard deviation step
- the acceptable window size can be set in a range from 30 degrees to 90 degrees on either side of the target (extended to account for the current rotation)

**Comment by juliusjgm12** [comment]
Completed but requires testing.
