### ISSUE TITLE
make custom icons proportional

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#70]
Right now, the custom icons are squished / stretched into a square, but the expected behavior is that a non-square icon remains non-square. In the current set of example icons, this is most clearly seen in the soccer goal (target_2.png).

**Comment by juliusjgm12** [comment]
requires PIL library
not sure if the lab's computers already have PIL -- they probably do --

**Comment by thartbm** [comment]
I strongly doubt that requires PIL. PsychoPy has options for displaying images at various scales:

http://www.psychopy.org/api/visual/imagestim.html?highlight=visual%20stim#psychopy.visual.ImageStim.size

**Comment by juliusjgm12** [comment]
Psychopy already uses a version of PIL called pillow so it isn't really
redundant to use it.

I just use it to find the aspect ratio of the image before creating the
imagestim object.

I can modify it to create the object first and then find aspect ratio to
resize from there but I feel like that would be slower then using the PIL
module directly.

What do you think?

**Comment by thartbm** [comment]
Sounds good in principle. I'd like to check if there is not a simpler PsychoPy (or maybe numpy / scipy?) method that can be used to do this.
