### ISSUE TITLE
Add average and standard deviation column to pre-processing output

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#76]
After outlier removal, but before rounding to 2 decimals (or is that done in the write_csv anyway?) it would be nice to add two columns to the data frame (on the right side, so there is no re-ordering of existing columns).

The first should have the average cursor error (or reach deviation) across all participants for that trial / block / target.

The second should have the standard deviation of the cursor errors (or reach deviations) across all participants for that trial / block / target.

**Comment by juliusjgm12** [comment]
Added
