### ISSUE TITLE
2 Experiments freezing on first trial

### ISSUE THREAD

**Issue by ambikabansal** [thartbm/PyVMEC#82]
Two of the conditions are freezing after the first trial. I used the 'duplicate button' to create all 8 conditions, yet only these 2 that are not working. The other 6 conditions are running fine.
I have attached the error messages I am getting here.

![img_0181](https://user-images.githubusercontent.com/43055607/48499900-8b0b7880-e807-11e8-9939-345627788141.JPG)
![img_0182](https://user-images.githubusercontent.com/43055607/48499904-8fd02c80-e807-11e8-939c-436ce3714f93.JPG)

**Comment by thartbm** [comment]
Solved.
