### ISSUE TITLE
Branch 0.9.2 to 0.9.3?

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#84]
Task related stuff seems to be about done. Let's switch to polishing the data processing part.

First thing, new branch:
- Branch off 0.9.2 to 0.9.3
- Preserve 0.9.2 (is that even necessary?)
- Merge 0.9.2 into the master branch
- Start working on 0.9.3

**Comment by juliusjgm12** [comment]
I think it is safer to preserve 0.9.2 since Ambika and Shanaa are using that most current version for running their experiments.

**Comment by juliusjgm12** [comment]
branch 0.9.3 up now
