### ISSUE TITLE
Function to compare JSONs

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#85]
Do this AFTER the JSONs have been cleaned up.

Make a function that returns true if the tasks and experiment wide settings in two PyVMEC JSONs are exactly the same. For tasks this also includes task names, as they are used for analysis, and pause tasks, as they may affect later behavior.

The functions should return false if there is a difference between the two.

It should ignore parts of the task definition that are not used, and it should ignore the participant list. Both of these should not be there in the first place, so cleaning up the JSONs will help with getting this functional.

**Comment by juliusjgm12** [comment]
Made a function called compare in the GUI.py that does this. It takes two arguments, a participant name and an experiment (full experiment dictionary). It returns True or False depending on if the json file in the given participant is the same as the given experiment.
