### ISSUE TITLE
Write function that creates the complete data file for a participant

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#88]
The functionality that goes through a participant's data folder to collect all data and create the combined file, should be in a separate function.

It should be called when an experiment is finished.

But there should also be a button with the participant list to 'recombine data'. This should only apply for participants with a complete dataset. (That means that maybe we can overload the 'continue run' button to show/do 'continue run' for participants with incomplete data, and show/do 'recombine data' for participants with complete data? Or is that too confusing?)

**Comment by juliusjgm12** [comment]
I made a second button underneath the continue run button for recombining data. It disables and enables depending on if that participant has full a complete data set or not.
