### ISSUE TITLE
rotated error-clamp trials end on distance criteria

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#91]
Problem: when error-clamped trials are rotated, the trials can't be completed because you can never reach the target with your rotated cursor.

Perhaps the criterion for error-clamp trials to end should not be to get the cursor on the target, but to get the cursor to the distance the target is at. Or alternatively, do the criterion on a zero-clamped cursor, that is calculated before the clamped cursor is rotated for the display? Not sure what would be the best solution.

**Comment by juliusjgm12** [comment]
Oh i thought I tested this already, I guess not. The code is already there for detecting the cursor at a distance the target is at, but i suppose i forgot to implement it for the error-clamped terminal feedback case.

**Comment by juliusjgm12** [comment]
Nevermind, I misread and thought you meant it wasn't working for error-clamped terminal feedback trials. I understand. I think i'll make the criterion the former you detailed.
