### ISSUE TITLE
Pre-processing error

### ISSUE THREAD

**Issue by thartbm** [thartbm/PyVMEC#94]
Using the data from the toy task to test pre-processing, I get an error:

```
Traceback (most recent call last):
  File "/home/marius/Science/PyVMEC/PyVMEC/GUI.py", line 1908, in preprocess_button_click
    preprocessed_data = pp.process_participants(self.participant_list_dynamic, self.task_list_dynamic, self.Parent.experiment_holder, self.cfg)
  File "/home/marius/Science/PyVMEC/PyVMEC/Preprocess.py", line 172, in process_participants
    if int(row[2]) >= 0:
ValueError: invalid literal for int() with base 10: ''
```

I have copied the JSON into the directory of each participant. It was never changed, so that should have worked. However, something seems to be empty now... I'm not sure if that is data being read in, or the list of participants.

Here is the dataset I'm working with:
[preprocessing.zip](https://github.com/thartbm/PyVMEC/files/2631769/preprocessing.zip)

**Comment by juliusjgm12** [comment]
I see what happened.

The issue is within error-clamp trials on old data.

Old raw data had no values for rotation angle. This is only an issue in old data but it causes an issue since pre-processing checks that column for "integer" values.

I'll make a fix to set empty values to zero.

**Comment by juliusjgm12** [comment]
Should work now for that data set.
